LibraryManagementSystem/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using static System.Reflection.Metadata.BlobBuilder;

namespace LibraryManagementSystem.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryManagementContext _context;

        public BooksController(LibraryManagementContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString)
        {
            var role = HttpContext.Session.GetString("UserRole");
            ViewBag.UserRole = role;

            ViewData["CurrentFilter"] = searchString;

            var books = from b in _context.Books
                        select b;

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString) ||
                                         s.Author.Contains(searchString) ||
                                         s.Isbn.Contains(searchString));
            }

            return View(await books.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("BookId,Title,Author,Isbn,Category,PublishedDate,CopiesAvailable")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,Title,Author,Isbn,Category,PublishedDate,CopiesAvailable")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookId == id);
        }
    }
}

LibraryManagementSystem/Controllers/LibrariansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementSystem.Controllers
{
    public class LibrariansController : Controller
    {
        private readonly LibraryManagementContext _context;

        public LibrariansController(LibraryManagementContext context)
        {
            _context = context;
        }

        // GET: Librarians
        public async Task<IActionResult> Index()
        {
            return View(await _context.Librarians.ToListAsync());
        }

        // GET: Librarians/Details/5
        //[Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librarian = await _context.Librarians
                .FirstOrDefaultAsync(m => m.LibrarianId == id);
            if (librarian == null)
            {
                return NotFound();
            }

            return View(librarian);
        }

       
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Librarian lUser)
        {
            if(ModelState.IsValid)
            {
               await _context.Librarians.AddAsync(lUser);
                await _context.SaveChangesAsync();
                TempData["succerss"] = "Registerd Successfully";
                return RedirectToAction("Dashboard");
            }
            return View();
        }

     
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
               return RedirectToAction("Dashboard");
            }
            return View();
        }
        [HttpPost]
       
        public IActionResult Login(Librarian lUser)
        {
            var lib = _context.Librarians
                .Where(x => x.Email == lUser.Email && x.Password == lUser.Password).FirstOrDefault();
            if (lib != null)
            {
                HttpContext.Session.SetString("UserSession", lib.LibrarianId.ToString());
                HttpContext.Session.SetString("UserRole", "Librarian");                
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.Message = "Login failed";
            }
            return View();

        }

        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var LibId = int.Parse(HttpContext.Session.GetString("UserSession"));
                var lib = _context.Librarians.FirstOrDefault(m => m.LibrarianId == LibId);

                if (lib != null)
                {
                    ViewBag.librariansession = HttpContext.Session.GetString("UserSession");
                    return View(lib);
                }
            }

            return RedirectToAction("Login");
        }

        public IActionResult Logout()
        {
            if(HttpContext.Session.GetString("UserSession") != null)
            {
                HttpContext.Session.Remove("UserSession");
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Librarians/Edit/5
        //[Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librarian = await _context.Librarians.FindAsync(id);
            if (librarian == null)
            {
                return NotFound();
            }
            return View(librarian);
        }

        // POST: Librarians/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Edit(int id, [Bind("LibrarianId,Name,Email,Role,DateJoined,Password")] Librarian librarian)
        {
            if (id != librarian.LibrarianId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(librarian);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibrarianExists(librarian.LibrarianId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(librarian);
        }

        // GET: Librarians/Delete/5
        //[Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librarian = await _context.Librarians
                .FirstOrDefaultAsync(m => m.LibrarianId == id);
            if (librarian == null)
            {
                return NotFound();
            }

            return View(librarian);
        }

        // POST: Librarians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Librarian")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var librarian = await _context.Librarians.FindAsync(id);
            if (librarian != null)
            {
                _context.Librarians.Remove(librarian);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibrarianExists(int id)
        {
            return _context.Librarians.Any(e => e.LibrarianId == id);
        }
    }
}

LibraryManagementSystem/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Models;

namespace LibraryManagementSystem.Controllers
{
    public class MembersController : Controller
    {
        private readonly LibraryManagementContext _context;

        public MembersController(LibraryManagementContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var mber = from b in _context.Members
                        select b;

            if (!string.IsNullOrEmpty(searchString))
            {
                mber = mber.Where(s => s.Name.Contains(searchString) ||
                                         s.Email.Contains(searchString));
            }

            return View(await mber.ToListAsync());
        }



        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Member mUser)
        {
            if (ModelState.IsValid)
            {
                await _context.Members.AddAsync(mUser);
                await _context.SaveChangesAsync();
                TempData["succerss"] = "Registerd Successfully";
                return RedirectToAction("Dashboard");
            }
            return View();
        }
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Login(Member mUser)
        {
            var mber = _context.Members.FirstOrDefault(x=> x.Email == mUser.Email && x.Password == x.Password);
            if(mber != null)
            {
                HttpContext.Session.SetString("UserSession", mber.MemberId.ToString());
                HttpContext.Session.SetString("UserRole", "Member");
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.Message = "Login failed";
            }
            return View();
        }
        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var memberId = int.Parse(HttpContext.Session.GetString("UserSession"));
                var member = _context.Members.FirstOrDefault(m => m.MemberId == memberId);

                if (member != null)
                {
                    ViewBag.Membersession = HttpContext.Session.GetString("UserSession");
                    return View(member);
                }
            }

            return RedirectToAction("Login");
        }

        public IActionResult Logout()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                HttpContext.Session.Remove("UserSession");
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,Name,Email,Address,MembershipDate,Status,Password")] Member member)
        {
            if (id != member.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Dashboard));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var member = await _context.Members.FindAsync(id);
            if (member != null)
            {
                _context.Members.Remove(member);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Login");
        }

        private bool MemberExists(int id)
        {
            return _context.Members.Any(e => e.MemberId == id);
        }
    }
}

LibraryManagementSystem/Views/Librarians/Dashboard.cshtml
@model LibraryManagementSystem.Models.Librarian
@{
    ViewData["Title"] = "Dashboard";
}
<link href="~/css/dashboardsheet.css" rel="stylesheet" />
<body>
    <div class="first">
        <div class="headline">
            <h2>Librarian Dashboard</h2>
            <a asp-controller="Librarians" asp-action="Logout" class="logout-button">Logout</a>
        </div>
        <div class="dashboard-first">
            <h3>@Model.Name</h3>
            @if (TempData["succerss"] != null)
            {
                <p class="success-message">@TempData["succerss"]</p>
            }
            <div class="button-container">
				<a class="dashboard-button" asp-controller="Books" asp-action="Index">View Books</a>
                <a class="dashboard-button" asp-controller="Librarians" asp-action="Details" asp-route-id="@Model.LibrarianId">Profile</a>
                <a class="dashboard-button" asp-controller="Members" asp-action="Index">View Members</a>
            </div>
        </div>
    </div>
</body>

LibraryManagementSystem/Views/Librarians/Delete.cshtml
@model LibraryManagementSystem.Models.Librarian

@{
    ViewData["Title"] = "Delete";
}

<title>@ViewData["Title"]</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link href="~/css/detail_profilesheet.css" rel="stylesheet" />
<div class="main">
    <div class="first">
        <h1>Delete Account</h1>
        <div>
            <h4>Librarian</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Role)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Role)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.DateJoined)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DateJoined)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Password)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Password)
                </dd>
            </dl>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="LibrarianId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
        </form>
    </div>
</div>

LibraryManagementSystem/Views/Librarians/Details.cshtml
@model LibraryManagementSystem.Models.Librarian

@{
    ViewData["Title"] = "Details";
}
 <title>@ViewData["Title"]</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link href="~/css/detail_profilesheet.css" rel="stylesheet" />
<div class="main">
    <div class="first">
        <h1>Profile</h1>

        <div>
            <h4>Librarian</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Role)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Role)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.DateJoined)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.DateJoined)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Password)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Password)
                </dd>
            </dl>
        </div>
        <div>
            <a asp-action="Edit" asp-route-id="@Model?.LibrarianId" class="edit-button">Edit Profile</a>

        </div>
    </div>
</div>

LibraryManagementSystem/Views/Librarians/Edit.cshtml
@model LibraryManagementSystem.Models.Librarian

@{
    ViewData["Title"] = "Edit";
}
<link href="~/css/edit_profilesheet.css" rel="stylesheet" />
<title>@ViewData["Title"]</title>
<div class="main">
    <div class="first">
        <div class="headline">
            <h1 class="h4">Edit Profile</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LibrarianId" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Role" class="control-label"></label>
                        <input asp-for="Role" class="form-control" />
                        <span asp-validation-for="Role" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateJoined" class="control-label"></label>
                        <input asp-for="DateJoined" class="form-control" />
                        <span asp-validation-for="DateJoined" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </form>
                <br />
                <a class="btn btn-danger mb-3" asp-action="Delete" asp-route-id="@Model?.LibrarianId">Delete</a>
            </div>
        </div>
    </div>
</div>

LibraryManagementSystem/Views/Librarians/Index.cshtml
@model IEnumerable<LibraryManagementSystem.Models.Librarian>

@{
    ViewData["Title"] = "Index";
}

<link href="~/css/dashboardsheet.css" rel="stylesheet" />
<body>
    <div class="first">
        <div class="headline">
            <h2>Librarian space</h2>
        </div>
        <div class="dashboard-first">
            <div class="button-container">
                <a class="dashboard-button" asp-controller="Librarians" asp-action="Login">Login For Librarian</a>
                <a class="dashboard-button" asp-controller="Librarians" asp-action="Register">Register as Librarian</a>
            </div>
        </div>
    </div>
</body>

LibraryManagementSystem/Views/Librarians/Login.cshtml
@model LibraryManagementSystem.Models.Librarian

@{
    ViewData["Title"] = "Login";
}

<title>@ViewData["Title"]</title>
<link href="~/css/loginsheet.css" rel="stylesheet" />

<div class="main">
    <div class="first">
        <div class="headline">
            <h1 class="h4">Librarian Login</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                @{
                    if (ViewBag.Message != null)
                    {
                        <p class="text-danger">@ViewBag.Message</p>
                    }
                }
                <form asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" type="password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary btn-block" />
                    </div>
                </form>
                <p class="text-center">
                    <a asp-controller="Members" asp-action="Register" class="btn-custom">Not Registered Yet? Sign Up</a>
                </p>
            </div>
        </div>
    </div>

</div>

LibraryManagementSystem/Views/Librarians/Register.cshtml
@model LibraryManagementSystem.Models.Librarian

@{
    ViewData["Title"] = "Register";
}

<title>@ViewData["Title"]</title>
<link href="~/css/registersheet.css" rel="stylesheet" />
<div class="main">
    <div class="first">
        <div class="headline">
            <h1 class="h4">Librarian Registration</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Register">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Role" class="control-label"></label>
                        <input asp-for="Role" class="form-control" />
                        <span asp-validation-for="Role" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateJoined" class="control-label"></label>
                        <input asp-for="DateJoined" class="form-control" />
                        <span asp-validation-for="DateJoined" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" type="password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Register" class="btn btn-primary btn-block" />
                    </div>
                </form>
                <p class="text-center">
                    <a asp-controller="Librarians" asp-action="Login" class="btn-custom">Already Registered? Login</a>
                </p>
            </div>
        </div>
    </div>
</div>